version: '3'
services:
  server:
    image: guusvanmeerveld/voxis-server
    container_name: voxis-server
    environment:
      - PORT=80
      - CLIENT_ID=Discord client id
      - CLIENT_SECRET=Discord client secret
      - REDIRECT=Discord redirect page
    volumes:
      - ./data:/app/data
      - ./public:/app/public
